# ----------------------------------------------------------------------------
# Copyright (c) 2016-2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

# flake8: noqa

MAP_2023 = {
    # 2023.2 DISTRO
    'distro/core/qiime2-2023.2-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.2/release/qiime2-2023.2-py38-osx-conda.yml',
    'distro/core/qiime2-2023.2-py38-linux-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.2/release/qiime2-2023.2-py38-linux-conda.yml',

    # 2023.2
    '2023.2/common/gg-13-8-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/gg-13-8-99-515-806-nb-classifier.qza',
    '2023.2/common/gg-13-8-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/gg-13-8-99-515-806-nb-weighted-classifier.qza',
    '2023.2/common/gg-13-8-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/gg-13-8-99-nb-classifier.qza',
    '2023.2/common/gg-13-8-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/gg-13-8-99-nb-weighted-classifier.qza',
    '2023.2/common/sepp-refs-gg-13-8.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/sepp-refs-gg-13-8.qza',
    '2023.2/common/sepp-refs-silva-128.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/sepp-refs-silva-128.qza',
    '2023.2/common/silva-138-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/silva-138-99-515-806-nb-classifier.qza',
    '2023.2/common/silva-138-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/silva-138-99-515-806-nb-weighted-classifier.qza',
    '2023.2/common/silva-138-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/silva-138-99-nb-classifier.qza',
    '2023.2/common/silva-138-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/common/silva-138-99-nb-weighted-classifier.qza',
    '2023.2/common/silva-138-99-seqs-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/common/silva-138-99-seqs-515-806.qza',
    '2023.2/common/silva-138-99-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/common/silva-138-99-seqs.qza',
    '2023.2/common/silva-138-99-tax-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/common/silva-138-99-tax-515-806.qza',
    '2023.2/common/silva-138-99-tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/common/silva-138-99-tax.qza',
    '2023.2/tutorials/atacama-soils/10p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/10p/barcodes.fastq.gz',
    '2023.2/tutorials/atacama-soils/10p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/10p/forward.fastq.gz',
    '2023.2/tutorials/atacama-soils/10p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/10p/reverse.fastq.gz',
    '2023.2/tutorials/atacama-soils/1p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/1p/barcodes.fastq.gz',
    '2023.2/tutorials/atacama-soils/1p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/1p/forward.fastq.gz',
    '2023.2/tutorials/atacama-soils/1p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/atacama-soils/1p/reverse.fastq.gz',
    '2023.2/tutorials/chimera/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/chimera/atacama-table.qza',
    '2023.2/tutorials/chimera/atacama-rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/chimera/atacama-rep-seqs.qza',
    '2023.2/tutorials/exporting/feature-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/exporting/feature-table.qza',
    '2023.2/tutorials/exporting/unrooted-tree.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/exporting/unrooted-tree.qza',
    '2023.2/tutorials/filtering/distance-matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/filtering/distance-matrix.qza',
    '2023.2/tutorials/filtering/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/filtering/table.qza',
    '2023.2/tutorials/filtering/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/filtering/taxonomy.qza',
    '2023.2/tutorials/filtering/sequences.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/filtering/sequences.qza',
    '2023.2/tutorials/fmt/fmt-tutorial-demux-1-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/fmt/fmt-tutorial-demux-1-10p.qza',
    '2023.2/tutorials/fmt/fmt-tutorial-demux-1-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/fmt/fmt-tutorial-demux-1-1p.qza',
    '2023.2/tutorials/fmt/fmt-tutorial-demux-2-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/fmt/fmt-tutorial-demux-2-10p.qza',
    '2023.2/tutorials/fmt/fmt-tutorial-demux-2-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/fmt/fmt-tutorial-demux-2-1p.qza',
    '2023.2/tutorials/fmt-cdiff-khanna/manifest.csv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/fmt-cdiff-khanna/manifest.csv',
    '2023.2/tutorials/fmt-cdiff-khanna/sequence_files.zip':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/fmt-cdiff-khanna/sequence_files.zip',
    '2023.2/tutorials/gneiss/sample-metadata.tsv':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/gneiss/sample-metadata.tsv',
    '2023.2/tutorials/gneiss/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/gneiss/table.qza',
    '2023.2/tutorials/gneiss/taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/gneiss/taxa.qza',
    '2023.2/tutorials/importing/aligned-sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/aligned-sequences.fna',
    '2023.2/tutorials/importing/casava-18-paired-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/casava-18-paired-end-demultiplexed.zip',
    '2023.2/tutorials/importing/casava-18-single-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/casava-18-single-end-demultiplexed.zip',
    '2023.2/tutorials/importing/feature-table-v100.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/feature-table-v100.biom',
    '2023.2/tutorials/importing/feature-table-v210.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/feature-table-v210.biom',
    '2023.2/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz',
    '2023.2/tutorials/importing/pe-64-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/pe-64-manifest',
    '2023.2/tutorials/importing/pe-64.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/pe-64.zip',
    '2023.2/tutorials/importing/se-33-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/se-33-manifest',
    '2023.2/tutorials/importing/se-33.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/se-33.zip',
    '2023.2/tutorials/importing/sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/sequences.fna',
    '2023.2/tutorials/importing/unrooted-tree.tre':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/unrooted-tree.tre',
    '2023.2/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz',
    '2023.2/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz',
    '2023.2/tutorials/longitudinal/ecam_table_taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/longitudinal/ecam_table_taxa.qza',
    '2023.2/tutorials/longitudinal/ecam_shannon.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/longitudinal/ecam_shannon.qza',
    '2023.2/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza',
    '2023.2/tutorials/longitudinal/ecam_table_maturity.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/longitudinal/ecam_table_maturity.qza',
    '2023.2/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz',
    '2023.2/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz',
    '2023.2/tutorials/metadata/faith_pd_vector.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/metadata/faith_pd_vector.qza',
    '2023.2/tutorials/metadata/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/metadata/rep-seqs.qza',
    '2023.2/tutorials/metadata/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/metadata/taxonomy.qza',
    '2023.2/tutorials/metadata/unweighted_unifrac_pcoa_results.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/metadata/unweighted_unifrac_pcoa_results.qza',
    '2023.2/tutorials/otu-clustering/seqs.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/otu-clustering/seqs.fna',
    '2023.2/tutorials/otu-clustering/85_otus.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/otu-clustering/85_otus.qza',
    '2023.2/tutorials/pd-mice/animal_distal_gut.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/pd-mice/animal_distal_gut.qza',
    '2023.2/tutorials/pd-mice/demultiplexed_seqs.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/pd-mice/demultiplexed_seqs.zip',
    '2023.2/tutorials/pd-mice/manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/pd-mice/manifest',
    '2023.2/tutorials/pd-mice/ref_seqs_v4.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/pd-mice/ref_seqs_v4.qza',
    '2023.2/tutorials/pd-mice/ref_tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/pd-mice/ref_tax.qza',
    '2023.2/tutorials/quality-control/qc-mock-3-expected.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/quality-control/qc-mock-3-expected.qza',
    '2023.2/tutorials/quality-control/qc-mock-3-observed.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/quality-control/qc-mock-3-observed.qza',
    '2023.2/tutorials/quality-control/query-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/quality-control/query-seqs.qza',
    '2023.2/tutorials/quality-control/reference-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/quality-control/reference-seqs.qza',
    '2023.2/tutorials/quality-control/query-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/quality-control/query-table.qza',
    '2023.2/tutorials/read-joining/atacama-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/read-joining/atacama-seqs.qza',
    '2023.2/tutorials/read-joining/fj-joined.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/read-joining/fj-joined.zip',
    '2023.2/tutorials/sample-classifier/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/sample-classifier/atacama-table.qza',
    '2023.2/tutorials/sample-classifier/moving-pictures-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/sample-classifier/moving-pictures-table.qza',
    '2023.2/tutorials/training-feature-classifiers/85_otu_taxonomy.txt':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/training-feature-classifiers/85_otu_taxonomy.txt',
    '2023.2/tutorials/training-feature-classifiers/85_otus.fasta':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/training-feature-classifiers/85_otus.fasta',
    '2023.2/tutorials/training-feature-classifiers/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.2/tutorials/training-feature-classifiers/rep-seqs.qza',
    '2023.2/tutorials/phylogeny/rep-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/phylogeny/rep-seqs.qza',
    '2023.2/tutorials/utilities/faith-pd-vector.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/utilities/faith-pd-vector.qza',
    '2023.2/tutorials/utilities/jaccard-pcoa.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/utilities/jaccard-pcoa.qza',
    '2023.2/tutorials/utilities/taxa-barplot.qzv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.2/tutorials/utilities/taxa-barplot.qzv',
    '2023.2/tutorials/liao/fmt-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/fmt-metadata.tsv',
    '2023.2/tutorials/liao/sample-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/sample-metadata.tsv',
    '2023.2/tutorials/liao/transplant-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/transplant-metadata.tsv',
    '2023.2/tutorials/liao/rep-seqs.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/rep-seqs.qza',
    '2023.2/tutorials/liao/full-feature-table.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/full-feature-table.qza',
    '2023.2/tutorials/liao/fastq-casava.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.2/tutorials/liao/fastq-casava.zip',

    # Sample Metadata (hosted on Google Sheets)
    ## All of the following tutorials use the *new* docs sharing menu, via "File -> Publish to the Web" dialog for TSV export.

    ## FMT
    '2023.2/tutorials/fmt/sample_metadata':
        'https://docs.google.com/spreadsheets/d/15dbbxb8T7cZ3iHBsS4511IVWVE4-vwC6yG-v0Cyn8js/edit?usp=sharing',
    '2023.2/tutorials/fmt/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vSuwSudEIC-gUBR7pVakJSc7461a1fjRP543jitwNczNTEJoHALr-i25FyWb8aHu9lizRsbnBZlPMPN/pub?gid=0&single=true&output=tsv',

    ## Moving Pictures
    '2023.2/tutorials/moving-pictures/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1I9TzFqkjQ9RvXMrP7StbWwMid5pjFN8exYC7nUVpKFs/edit?usp=sharing',
    '2023.2/tutorials/moving-pictures/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vTDeMqrgOV0OAB8XUJnS_1ULbIgAIbEUuaM5MMGnx8B2S0QzBgYSwPsKw_O_KzZ9rC50IcgIcc4924S/pub?gid=0&single=true&output=tsv',

    ## Atacama
    '2023.2/tutorials/atacama-soils/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1bnsQ8ECdfnSBr0VjBiT2RLOn5WH6Uf5i6I06zJjXaEA/edit?usp=sharing',
    '2023.2/tutorials/atacama-soils/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQDdJGnw-zyj-xUwkWiUVpRTbVry9d8tUKGkwQ5o6TrH6gypxeIJ6nNnju54_KZq51eahbddyFyGrhT/pub?gid=0&single=true&output=tsv',

    ## Longitudinal
    '2023.2/tutorials/longitudinal/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1BeS5mi1f-y_tUhZbibexhCmRkAGjFpPnPrfxT0FgvK8/edit?usp=sharing',
    '2023.2/tutorials/longitudinal/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vT-GQAKqsQx-ZLwWt4DJ6_VIqHtAtVEj3LWmYzXRki8NE_ElVvsge3vz3qNq03i-vJPp6bybuDo6z42/pub?gid=1303657428&single=true&output=tsv',

    ## PD Mice
    '2023.2/tutorials/pd-mice/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1TmrdCamol0QnSeS8RdHkTVMHq4XR5f218wxreOLY2V0/edit?usp=sharing',
    '2023.2/tutorials/pd-mice/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vS-8u08T5G9MKBGBGQ2RvUZ0v17MDk9XDVqQKCnnTa2xd5-yWTANdHifVY9ZJEzRpJs9g6M8-ghhbp5/pub?gid=1509704122&single=true&output=tsv',

# 2023.5 DISTRO
    'distro/core/qiime2-2023.5-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.5/release/qiime2-2023.5-py38-osx-conda.yml',
    'distro/core/qiime2-2023.5-py38-linux-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.5/release/qiime2-2023.5-py38-linux-conda.yml',
    'distro/core/2023.5':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/core/qiime20235-{BUILDID}.zip',
    'distro/core/qiime20235-{BUILDID}.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/core/qiime20235-{BUILDID}.zip',

    # 2023.5
    '2023.5/common/gg-13-8-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/gg-13-8-99-515-806-nb-classifier.qza',
    '2023.5/common/gg-13-8-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/gg-13-8-99-515-806-nb-weighted-classifier.qza',
    '2023.5/common/gg-13-8-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/gg-13-8-99-nb-classifier.qza',
    '2023.5/common/gg-13-8-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/gg-13-8-99-nb-weighted-classifier.qza',
    '2023.5/common/sepp-refs-gg-13-8.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/sepp-refs-gg-13-8.qza',
    '2023.5/common/sepp-refs-silva-128.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/sepp-refs-silva-128.qza',
    '2023.5/common/silva-138-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/silva-138-99-515-806-nb-classifier.qza',
    '2023.5/common/silva-138-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/silva-138-99-515-806-nb-weighted-classifier.qza',
    '2023.5/common/silva-138-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/silva-138-99-nb-classifier.qza',
    '2023.5/common/silva-138-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/common/silva-138-99-nb-weighted-classifier.qza',
    '2023.5/common/silva-138-99-seqs-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/common/silva-138-99-seqs-515-806.qza',
    '2023.5/common/silva-138-99-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/common/silva-138-99-seqs.qza',
    '2023.5/common/silva-138-99-tax-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/common/silva-138-99-tax-515-806.qza',
    '2023.5/common/silva-138-99-tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/common/silva-138-99-tax.qza',
    '2023.5/tutorials/atacama-soils/10p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/10p/barcodes.fastq.gz',
    '2023.5/tutorials/atacama-soils/10p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/10p/forward.fastq.gz',
    '2023.5/tutorials/atacama-soils/10p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/10p/reverse.fastq.gz',
    '2023.5/tutorials/atacama-soils/1p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/1p/barcodes.fastq.gz',
    '2023.5/tutorials/atacama-soils/1p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/1p/forward.fastq.gz',
    '2023.5/tutorials/atacama-soils/1p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/atacama-soils/1p/reverse.fastq.gz',
    '2023.5/tutorials/chimera/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/chimera/atacama-table.qza',
    '2023.5/tutorials/chimera/atacama-rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/chimera/atacama-rep-seqs.qza',
    '2023.5/tutorials/exporting/feature-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/exporting/feature-table.qza',
    '2023.5/tutorials/exporting/unrooted-tree.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/exporting/unrooted-tree.qza',
    '2023.5/tutorials/filtering/distance-matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/filtering/distance-matrix.qza',
    '2023.5/tutorials/filtering/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/filtering/table.qza',
    '2023.5/tutorials/filtering/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/filtering/taxonomy.qza',
    '2023.5/tutorials/filtering/sequences.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/filtering/sequences.qza',
    '2023.5/tutorials/fmt/fmt-tutorial-demux-1-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/fmt/fmt-tutorial-demux-1-10p.qza',
    '2023.5/tutorials/fmt/fmt-tutorial-demux-1-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/fmt/fmt-tutorial-demux-1-1p.qza',
    '2023.5/tutorials/fmt/fmt-tutorial-demux-2-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/fmt/fmt-tutorial-demux-2-10p.qza',
    '2023.5/tutorials/fmt/fmt-tutorial-demux-2-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/fmt/fmt-tutorial-demux-2-1p.qza',
    '2023.5/tutorials/fmt-cdiff-khanna/manifest.csv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/fmt-cdiff-khanna/manifest.csv',
    '2023.5/tutorials/fmt-cdiff-khanna/sequence_files.zip':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/fmt-cdiff-khanna/sequence_files.zip',
    '2023.5/tutorials/gneiss/sample-metadata.tsv':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/gneiss/sample-metadata.tsv',
    '2023.5/tutorials/gneiss/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/gneiss/table.qza',
    '2023.5/tutorials/gneiss/taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/gneiss/taxa.qza',
    '2023.5/tutorials/importing/aligned-sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/aligned-sequences.fna',
    '2023.5/tutorials/importing/casava-18-paired-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/casava-18-paired-end-demultiplexed.zip',
    '2023.5/tutorials/importing/casava-18-single-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/casava-18-single-end-demultiplexed.zip',
    '2023.5/tutorials/importing/feature-table-v100.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/feature-table-v100.biom',
    '2023.5/tutorials/importing/feature-table-v210.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/feature-table-v210.biom',
    '2023.5/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz',
    '2023.5/tutorials/importing/pe-64-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/pe-64-manifest',
    '2023.5/tutorials/importing/pe-64.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/pe-64.zip',
    '2023.5/tutorials/importing/se-33-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/se-33-manifest',
    '2023.5/tutorials/importing/se-33.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/se-33.zip',
    '2023.5/tutorials/importing/sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/sequences.fna',
    '2023.5/tutorials/importing/unrooted-tree.tre':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/unrooted-tree.tre',
    '2023.5/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz',
    '2023.5/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz',
    '2023.5/tutorials/longitudinal/ecam_table_taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/longitudinal/ecam_table_taxa.qza',
    '2023.5/tutorials/longitudinal/ecam_shannon.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/longitudinal/ecam_shannon.qza',
    '2023.5/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza',
    '2023.5/tutorials/longitudinal/ecam_table_maturity.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/longitudinal/ecam_table_maturity.qza',
    '2023.5/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz',
    '2023.5/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz',
    '2023.5/tutorials/metadata/faith_pd_vector.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/metadata/faith_pd_vector.qza',
    '2023.5/tutorials/metadata/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/metadata/rep-seqs.qza',
    '2023.5/tutorials/metadata/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/metadata/taxonomy.qza',
    '2023.5/tutorials/metadata/unweighted_unifrac_pcoa_results.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/metadata/unweighted_unifrac_pcoa_results.qza',
    '2023.5/tutorials/otu-clustering/seqs.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/otu-clustering/seqs.fna',
    '2023.5/tutorials/otu-clustering/85_otus.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/otu-clustering/85_otus.qza',
    '2023.5/tutorials/pd-mice/animal_distal_gut.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/pd-mice/animal_distal_gut.qza',
    '2023.5/tutorials/pd-mice/demultiplexed_seqs.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/pd-mice/demultiplexed_seqs.zip',
    '2023.5/tutorials/pd-mice/manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/pd-mice/manifest',
    '2023.5/tutorials/pd-mice/ref_seqs_v4.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/pd-mice/ref_seqs_v4.qza',
    '2023.5/tutorials/pd-mice/ref_tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/pd-mice/ref_tax.qza',
    '2023.5/tutorials/quality-control/qc-mock-3-expected.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/quality-control/qc-mock-3-expected.qza',
    '2023.5/tutorials/quality-control/qc-mock-3-observed.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/quality-control/qc-mock-3-observed.qza',
    '2023.5/tutorials/quality-control/query-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/quality-control/query-seqs.qza',
    '2023.5/tutorials/quality-control/reference-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/quality-control/reference-seqs.qza',
    '2023.5/tutorials/quality-control/query-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/quality-control/query-table.qza',
    '2023.5/tutorials/read-joining/atacama-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/read-joining/atacama-seqs.qza',
    '2023.5/tutorials/read-joining/fj-joined.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/read-joining/fj-joined.zip',
    '2023.5/tutorials/sample-classifier/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/sample-classifier/atacama-table.qza',
    '2023.5/tutorials/sample-classifier/moving-pictures-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/sample-classifier/moving-pictures-table.qza',
    '2023.5/tutorials/training-feature-classifiers/85_otu_taxonomy.txt':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/training-feature-classifiers/85_otu_taxonomy.txt',
    '2023.5/tutorials/training-feature-classifiers/85_otus.fasta':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/training-feature-classifiers/85_otus.fasta',
    '2023.5/tutorials/training-feature-classifiers/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.5/tutorials/training-feature-classifiers/rep-seqs.qza',
    '2023.5/tutorials/phylogeny/rep-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/phylogeny/rep-seqs.qza',
    '2023.5/tutorials/utilities/faith-pd-vector.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/utilities/faith-pd-vector.qza',
    '2023.5/tutorials/utilities/jaccard-pcoa.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/utilities/jaccard-pcoa.qza',
    '2023.5/tutorials/utilities/taxa-barplot.qzv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.5/tutorials/utilities/taxa-barplot.qzv',
    '2023.5/tutorials/liao/fmt-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/fmt-metadata.tsv',
    '2023.5/tutorials/liao/sample-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/sample-metadata.tsv',
    '2023.5/tutorials/liao/transplant-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/transplant-metadata.tsv',
    '2023.5/tutorials/liao/rep-seqs.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/rep-seqs.qza',
    '2023.5/tutorials/liao/full-feature-table.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/full-feature-table.qza',
    '2023.5/tutorials/liao/fastq-casava.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.5/tutorials/liao/fastq-casava.zip',

    # Sample Metadata (hosted on Google Sheets)
    ## All of the following tutorials use the *new* docs sharing menu, via "File -> Publish to the Web" dialog for TSV export.

    ## FMT
    '2023.5/tutorials/fmt/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1WCHq1dxJXl2Igz5u2pDSdNTm2PJrhuP4H-5i83fDMXQ/edit?usp=sharing',
    '2023.5/tutorials/fmt/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vRyW3tweGCRMeHpOqiHy7_ysKKglserCSQmG6ZO1zhha9MUJorpDCoNRlyvghygT1yigRsPEE5X6I5Y/pub?gid=0&single=true&output=tsv',

    ## Moving Pictures
    '2023.5/tutorials/moving-pictures/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1OzRCFzwiCCHzWKchYfzXQ-dBguRoQ5g2gmvZztxgFLA/edit?usp=sharing',
    '2023.5/tutorials/moving-pictures/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQq4S-WmpFld87Nm4_YSo-RPPoC-3Mv-cR3pcwse4jbVP1QWsZ9yBEh1PasojiDLc25G7Iq7d9hghdK/pub?gid=0&single=true&output=tsv',

    ## Atacama
    '2023.5/tutorials/atacama-soils/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1xTHut3-Q1tDcJh8EOr4BB83IRqrN5Haa0tZxAJzJhVU/edit?usp=sharing',
    '2023.5/tutorials/atacama-soils/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vToYo49lgVTny-WnKfyWocjkzPA0fTHNQKTS_AxYobSWvDuSe4iHCsAi7pDJOBMP0-BbR0WH4lBfdTz/pub?gid=0&single=true&output=tsv',

    ## Longitudinal
    '2023.5/tutorials/longitudinal/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1z-VxPtWefgBrONIHucHqLlWRy9xOhpMYkodGcbDX5Rw/edit?usp=sharing',
    '2023.5/tutorials/longitudinal/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQclbs4CzBfJ7z5_CFZJCRhHUeFDTlmFz4yHFeQqxmbmubxHs20A4akU1pxRUIoNOwOjsuupscPjgqM/pub?gid=1303657428&single=true&output=tsv',

    ## PD Mice
    '2023.5/tutorials/pd-mice/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1me5GWzn6ua5RLzHVnoclY-s4yv66DpUBi8MtlgiW9EQ/edit?usp=sharing',
    '2023.5/tutorials/pd-mice/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQH04jrXQddOv0QPkk6_9-kwiNYfbdcCmh4nX79RnfIOqtC-VVIWrEh2Pkl9y49JHb6Oy2a2390-oKL/pub?gid=1509704122&single=true&output=tsv',

# 2023.7 DISTRO
    'distro/core/qiime2-2023.7-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.7/release/qiime2-2023.7-py38-osx-conda.yml',
    'distro/core/qiime2-2023.7-py38-linux-conda.yml':
        'https://raw.githubusercontent.com/qiime2/environment-files/master/2023.7/release/qiime2-2023.7-py38-linux-conda.yml',
    'distro/core/2023.7':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/core/qiime20237-{BUILDID}.zip',
    'distro/core/qiime20237-{BUILDID}.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/core/qiime20237-{BUILDID}.zip',

    # 2023.7
    '2023.7/common/gg-13-8-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/gg-13-8-99-515-806-nb-classifier.qza',
    '2023.7/common/gg-13-8-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/gg-13-8-99-515-806-nb-weighted-classifier.qza',
    '2023.7/common/gg-13-8-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/gg-13-8-99-nb-classifier.qza',
    '2023.7/common/gg-13-8-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/gg-13-8-99-nb-weighted-classifier.qza',
    '2023.7/common/sepp-refs-gg-13-8.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/sepp-refs-gg-13-8.qza',
    '2023.7/common/sepp-refs-silva-128.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/sepp-refs-silva-128.qza',
    '2023.7/common/silva-138-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/silva-138-99-515-806-nb-classifier.qza',
    '2023.7/common/silva-138-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/silva-138-99-515-806-nb-weighted-classifier.qza',
    '2023.7/common/silva-138-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/silva-138-99-nb-classifier.qza',
    '2023.7/common/silva-138-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/common/silva-138-99-nb-weighted-classifier.qza',
    '2023.7/common/silva-138-99-seqs-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/common/silva-138-99-seqs-515-806.qza',
    '2023.7/common/silva-138-99-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/common/silva-138-99-seqs.qza',
    '2023.7/common/silva-138-99-tax-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/common/silva-138-99-tax-515-806.qza',
    '2023.7/common/silva-138-99-tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/common/silva-138-99-tax.qza',
    '2023.7/tutorials/atacama-soils/10p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/10p/barcodes.fastq.gz',
    '2023.7/tutorials/atacama-soils/10p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/10p/forward.fastq.gz',
    '2023.7/tutorials/atacama-soils/10p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/10p/reverse.fastq.gz',
    '2023.7/tutorials/atacama-soils/1p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/1p/barcodes.fastq.gz',
    '2023.7/tutorials/atacama-soils/1p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/1p/forward.fastq.gz',
    '2023.7/tutorials/atacama-soils/1p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/atacama-soils/1p/reverse.fastq.gz',
    '2023.7/tutorials/chimera/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/chimera/atacama-table.qza',
    '2023.7/tutorials/chimera/atacama-rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/chimera/atacama-rep-seqs.qza',
    '2023.7/tutorials/exporting/feature-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/exporting/feature-table.qza',
    '2023.7/tutorials/exporting/unrooted-tree.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/exporting/unrooted-tree.qza',
    '2023.7/tutorials/filtering/distance-matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/filtering/distance-matrix.qza',
    '2023.7/tutorials/filtering/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/filtering/table.qza',
    '2023.7/tutorials/filtering/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/filtering/taxonomy.qza',
    '2023.7/tutorials/filtering/sequences.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/filtering/sequences.qza',
    '2023.7/tutorials/fmt/fmt-tutorial-demux-1-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/fmt/fmt-tutorial-demux-1-10p.qza',
    '2023.7/tutorials/fmt/fmt-tutorial-demux-1-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/fmt/fmt-tutorial-demux-1-1p.qza',
    '2023.7/tutorials/fmt/fmt-tutorial-demux-2-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/fmt/fmt-tutorial-demux-2-10p.qza',
    '2023.7/tutorials/fmt/fmt-tutorial-demux-2-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/fmt/fmt-tutorial-demux-2-1p.qza',
    '2023.7/tutorials/fmt-cdiff-khanna/manifest.csv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/fmt-cdiff-khanna/manifest.csv',
    '2023.7/tutorials/fmt-cdiff-khanna/sequence_files.zip':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/fmt-cdiff-khanna/sequence_files.zip',
    '2023.7/tutorials/gneiss/sample-metadata.tsv':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/gneiss/sample-metadata.tsv',
    '2023.7/tutorials/gneiss/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/gneiss/table.qza',
    '2023.7/tutorials/gneiss/taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/gneiss/taxa.qza',
    '2023.7/tutorials/importing/aligned-sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/aligned-sequences.fna',
    '2023.7/tutorials/importing/casava-18-paired-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/casava-18-paired-end-demultiplexed.zip',
    '2023.7/tutorials/importing/casava-18-single-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/casava-18-single-end-demultiplexed.zip',
    '2023.7/tutorials/importing/feature-table-v100.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/feature-table-v100.biom',
    '2023.7/tutorials/importing/feature-table-v210.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/feature-table-v210.biom',
    '2023.7/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz',
    '2023.7/tutorials/importing/pe-64-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/pe-64-manifest',
    '2023.7/tutorials/importing/pe-64.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/pe-64.zip',
    '2023.7/tutorials/importing/se-33-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/se-33-manifest',
    '2023.7/tutorials/importing/se-33.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/se-33.zip',
    '2023.7/tutorials/importing/sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/sequences.fna',
    '2023.7/tutorials/importing/unrooted-tree.tre':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/unrooted-tree.tre',
    '2023.7/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz',
    '2023.7/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz',
    '2023.7/tutorials/longitudinal/ecam_table_taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/longitudinal/ecam_table_taxa.qza',
    '2023.7/tutorials/longitudinal/ecam_shannon.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/longitudinal/ecam_shannon.qza',
    '2023.7/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza',
    '2023.7/tutorials/longitudinal/ecam_table_maturity.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/longitudinal/ecam_table_maturity.qza',
    '2023.7/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz',
    '2023.7/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz',
    '2023.7/tutorials/metadata/faith_pd_vector.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/metadata/faith_pd_vector.qza',
    '2023.7/tutorials/metadata/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/metadata/rep-seqs.qza',
    '2023.7/tutorials/metadata/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/metadata/taxonomy.qza',
    '2023.7/tutorials/metadata/unweighted_unifrac_pcoa_results.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/metadata/unweighted_unifrac_pcoa_results.qza',
    '2023.7/tutorials/otu-clustering/seqs.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/otu-clustering/seqs.fna',
    '2023.7/tutorials/otu-clustering/85_otus.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/otu-clustering/85_otus.qza',
    '2023.7/tutorials/pd-mice/animal_distal_gut.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/pd-mice/animal_distal_gut.qza',
    '2023.7/tutorials/pd-mice/demultiplexed_seqs.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/pd-mice/demultiplexed_seqs.zip',
    '2023.7/tutorials/pd-mice/manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/pd-mice/manifest',
    '2023.7/tutorials/pd-mice/ref_seqs_v4.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/pd-mice/ref_seqs_v4.qza',
    '2023.7/tutorials/pd-mice/ref_tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/pd-mice/ref_tax.qza',
    '2023.7/tutorials/quality-control/qc-mock-3-expected.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/quality-control/qc-mock-3-expected.qza',
    '2023.7/tutorials/quality-control/qc-mock-3-observed.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/quality-control/qc-mock-3-observed.qza',
    '2023.7/tutorials/quality-control/query-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/quality-control/query-seqs.qza',
    '2023.7/tutorials/quality-control/reference-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/quality-control/reference-seqs.qza',
    '2023.7/tutorials/quality-control/query-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/quality-control/query-table.qza',
    '2023.7/tutorials/read-joining/atacama-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/read-joining/atacama-seqs.qza',
    '2023.7/tutorials/read-joining/fj-joined.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/read-joining/fj-joined.zip',
    '2023.7/tutorials/sample-classifier/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/sample-classifier/atacama-table.qza',
    '2023.7/tutorials/sample-classifier/moving-pictures-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/sample-classifier/moving-pictures-table.qza',
    '2023.7/tutorials/training-feature-classifiers/85_otu_taxonomy.txt':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/training-feature-classifiers/85_otu_taxonomy.txt',
    '2023.7/tutorials/training-feature-classifiers/85_otus.fasta':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/training-feature-classifiers/85_otus.fasta',
    '2023.7/tutorials/training-feature-classifiers/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.7/tutorials/training-feature-classifiers/rep-seqs.qza',
    '2023.7/tutorials/phylogeny/rep-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/phylogeny/rep-seqs.qza',
    '2023.7/tutorials/utilities/faith-pd-vector.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/utilities/faith-pd-vector.qza',
    '2023.7/tutorials/utilities/jaccard-pcoa.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/utilities/jaccard-pcoa.qza',
    '2023.7/tutorials/utilities/taxa-barplot.qzv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.7/tutorials/utilities/taxa-barplot.qzv',
    '2023.7/tutorials/liao/fmt-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/fmt-metadata.tsv',
    '2023.7/tutorials/liao/sample-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/sample-metadata.tsv',
    '2023.7/tutorials/liao/transplant-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/transplant-metadata.tsv',
    '2023.7/tutorials/liao/rep-seqs.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/rep-seqs.qza',
    '2023.7/tutorials/liao/full-feature-table.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/full-feature-table.qza',
    '2023.7/tutorials/liao/fastq-casava.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.7/tutorials/liao/fastq-casava.zip',

    # Sample Metadata (hosted on Google Sheets)
    ## All of the following tutorials use the *new* docs sharing menu, via "File -> Publish to the Web" dialog for TSV export.

    ## FMT
    '2023.7/tutorials/fmt/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1GsBO-0gU60pwr8-EDsW8ljT_kI0qy7uA4XwYONF6C1Y/edit?usp=sharing',
    '2023.7/tutorials/fmt/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vSkjF2D_qVwpa4DeVsZYxWrGFhcHs-OsrpZLekyaVD5u4eLEWTkjpqt1zD71s0QQ-d4FeZiuPoxiN2o/pub?gid=0&single=true&output=tsv',

    ## Moving Pictures
    '2023.7/tutorials/moving-pictures/sample_metadata':
        'https://docs.google.com/spreadsheets/d/14uVUAJh8zyH8CmnIgtK3IDwEPPANsXrxwuJqpRT79y4/edit?usp=sharing',
    '2023.7/tutorials/moving-pictures/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQQUqdGwFxHSUxYCGDDpm6m_FWFRQn8IbJmOl1Pgb1nHEUFVwz8HmvV6UXsXlUNfpq5aC6tqzJOZIwL/pub?gid=0&single=true&output=tsv',

    ## Atacama
    '2023.7/tutorials/atacama-soils/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1e6PMqIjaBuJgAHz6NWDY_kU2stD10CvKD_b7DIBALa4/edit?usp=sharing',
    '2023.7/tutorials/atacama-soils/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQkAumaxyrgAVIZ3JOkjgESN5bQ3ucP2y5xor7A3E8USK0RIfPXNZ2_FosbvELK2xYDVjFxRK41RT8A/pub?gid=0&single=true&output=tsv',

    ## Longitudinal
    '2023.7/tutorials/longitudinal/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1lC_CX2olhAD83U5cgAzLB5igaumfZ7JpggsPMJWoeFg/edit?usp=sharing',
    '2023.7/tutorials/longitudinal/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vRUTJ45bZHwuEF_Co3LSGd3DMJ6Zr225Q3YtV6XISMmpzlN_7skUZ0VmHkl0P2GK-MWp83_EwBB95aJ/pub?gid=1303657428&single=true&output=tsv',

    ## PD Mice
    '2023.7/tutorials/pd-mice/sample_metadata':
        'https://docs.google.com/spreadsheets/d/14RjnlRvfh3_ng5d04VKOcs2u3sLcWUqvWGrltbc1DpM/edit?usp=sharing',
    '2023.7/tutorials/pd-mice/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vRRqmgYtuTwTpQXnca92KT0pTQmE3Wb1ra5RNl4kLM3vgcUxaegOg23j-Wic1u59RjDzKF_-Q6ZxQtc/pub?gid=1509704122&single=true&output=tsv',

# 2023.9 DISTRO
    # Amplicon
    'distro/amplicon/qiime2-amplicon-2023.9-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/amplicon/released/qiime2-amplicon-macos-latest-conda.yml',
    'distro/amplicon/qiime2-amplicon-2023.9-py38-linux-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml',
    # Shotgun
    'distro/shotgun/qiime2-shotgun-2023.9-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/shotgun/released/qiime2-shotgun-macos-latest-conda.yml',
    'distro/shotgun/qiime2-shotgun-2023.9-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/shotgun/released/qiime2-shotgun-ubuntu-latest-conda.yml',
    # Tiny
    'distro/tiny/qiime2-tiny-2023.9-py38-osx-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/tiny/released/qiime2-tiny-macos-latest-conda.yml',
    'distro/tiny/qiime2-tiny-2023.9-py38-linux-conda.yml':
        'https://raw.githubusercontent.com/qiime2/distributions/dev/2023.9/tiny/released/qiime2-tiny-ubuntu-latest-conda.yml',

    # VMs
    # Amplicon
    'distro/amplicon/2023.9':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/amplicon/qiime20239-{BUILDID}.zip',
    'distro/amplicon/qiime20239-{BUILDID}.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/amplicon/qiime20239-{BUILDID}.zip',
    # Shotgun
    'distro/shotgun/2023.9':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/shotgun/qiime20239-{BUILDID}.zip',
    'distro/shotgun/qiime20239-{BUILDID}.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/shotgun/qiime20239-{BUILDID}.zip',
    # Tiny
    'distro/tiny/2023.9':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/tiny/qiime20239-{BUILDID}.zip',
    'distro/tiny/qiime20239-{BUILDID}.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/distro/tiny/qiime20239-{BUILDID}.zip',

    # 2023.9
    '2023.9/common/gg-13-8-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/gg-13-8-99-515-806-nb-classifier.qza',
    '2023.9/common/gg-13-8-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/gg-13-8-99-515-806-nb-weighted-classifier.qza',
    '2023.9/common/gg-13-8-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/gg-13-8-99-nb-classifier.qza',
    '2023.9/common/gg-13-8-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/gg-13-8-99-nb-weighted-classifier.qza',
    '2023.9/common/sepp-refs-gg-13-8.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/sepp-refs-gg-13-8.qza',
    '2023.9/common/sepp-refs-silva-128.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/sepp-refs-silva-128.qza',
    '2023.9/common/silva-138-99-515-806-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/silva-138-99-515-806-nb-classifier.qza',
    '2023.9/common/silva-138-99-515-806-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/silva-138-99-515-806-nb-weighted-classifier.qza',
    '2023.9/common/silva-138-99-nb-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/silva-138-99-nb-classifier.qza',
    '2023.9/common/silva-138-99-nb-weighted-classifier.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/common/silva-138-99-nb-weighted-classifier.qza',
    '2023.9/common/silva-138-99-seqs-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/common/silva-138-99-seqs-515-806.qza',
    '2023.9/common/silva-138-99-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/common/silva-138-99-seqs.qza',
    '2023.9/common/silva-138-99-tax-515-806.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/common/silva-138-99-tax-515-806.qza',
    '2023.9/common/silva-138-99-tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/common/silva-138-99-tax.qza',
    '2023.9/tutorials/atacama-soils/10p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/10p/barcodes.fastq.gz',
    '2023.9/tutorials/atacama-soils/10p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/10p/forward.fastq.gz',
    '2023.9/tutorials/atacama-soils/10p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/10p/reverse.fastq.gz',
    '2023.9/tutorials/atacama-soils/1p/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/1p/barcodes.fastq.gz',
    '2023.9/tutorials/atacama-soils/1p/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/1p/forward.fastq.gz',
    '2023.9/tutorials/atacama-soils/1p/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/atacama-soils/1p/reverse.fastq.gz',
    '2023.9/tutorials/chimera/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/chimera/atacama-table.qza',
    '2023.9/tutorials/chimera/atacama-rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/chimera/atacama-rep-seqs.qza',
    '2023.9/tutorials/exporting/feature-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/exporting/feature-table.qza',
    '2023.9/tutorials/exporting/unrooted-tree.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/exporting/unrooted-tree.qza',
    '2023.9/tutorials/filtering/distance-matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/filtering/distance-matrix.qza',
    '2023.9/tutorials/filtering/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/filtering/table.qza',
    '2023.9/tutorials/filtering/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/filtering/taxonomy.qza',
    '2023.9/tutorials/filtering/sequences.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/filtering/sequences.qza',
    '2023.9/tutorials/fmt/fmt-tutorial-demux-1-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/fmt/fmt-tutorial-demux-1-10p.qza',
    '2023.9/tutorials/fmt/fmt-tutorial-demux-1-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/fmt/fmt-tutorial-demux-1-1p.qza',
    '2023.9/tutorials/fmt/fmt-tutorial-demux-2-10p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/fmt/fmt-tutorial-demux-2-10p.qza',
    '2023.9/tutorials/fmt/fmt-tutorial-demux-2-1p.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/fmt/fmt-tutorial-demux-2-1p.qza',
    '2023.9/tutorials/fmt-cdiff-khanna/manifest.csv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/fmt-cdiff-khanna/manifest.csv',
    '2023.9/tutorials/fmt-cdiff-khanna/sequence_files.zip':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/fmt-cdiff-khanna/sequence_files.zip',
    '2023.9/tutorials/gneiss/sample-metadata.tsv':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/gneiss/sample-metadata.tsv',
    '2023.9/tutorials/gneiss/table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/gneiss/table.qza',
    '2023.9/tutorials/gneiss/taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/gneiss/taxa.qza',
    '2023.9/tutorials/importing/aligned-sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/aligned-sequences.fna',
    '2023.9/tutorials/importing/casava-18-paired-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/casava-18-paired-end-demultiplexed.zip',
    '2023.9/tutorials/importing/casava-18-single-end-demultiplexed.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/casava-18-single-end-demultiplexed.zip',
    '2023.9/tutorials/importing/feature-table-v100.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/feature-table-v100.biom',
    '2023.9/tutorials/importing/feature-table-v210.biom':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/feature-table-v210.biom',
    '2023.9/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/importing/muxed-se-barcode-in-seq.fastq.gz',
    '2023.9/tutorials/importing/pe-64-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/pe-64-manifest',
    '2023.9/tutorials/importing/pe-64.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/pe-64.zip',
    '2023.9/tutorials/importing/se-33-manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/se-33-manifest',
    '2023.9/tutorials/importing/se-33.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/se-33.zip',
    '2023.9/tutorials/importing/sequences.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/sequences.fna',
    '2023.9/tutorials/importing/unrooted-tree.tre':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/unrooted-tree.tre',
    '2023.9/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/muxed-pe-barcode-in-seq/forward.fastq.gz',
    '2023.9/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/importing/muxed-pe-barcode-in-seq/reverse.fastq.gz',
    '2023.9/tutorials/longitudinal/ecam_table_taxa.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/longitudinal/ecam_table_taxa.qza',
    '2023.9/tutorials/longitudinal/ecam_shannon.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/longitudinal/ecam_shannon.qza',
    '2023.9/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/longitudinal/unweighted_unifrac_distance_matrix.qza',
    '2023.9/tutorials/longitudinal/ecam_table_maturity.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/longitudinal/ecam_table_maturity.qza',
    '2023.9/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz',
    '2023.9/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz',
    '2023.9/tutorials/metadata/faith_pd_vector.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/metadata/faith_pd_vector.qza',
    '2023.9/tutorials/metadata/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/metadata/rep-seqs.qza',
    '2023.9/tutorials/metadata/taxonomy.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/metadata/taxonomy.qza',
    '2023.9/tutorials/metadata/unweighted_unifrac_pcoa_results.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/metadata/unweighted_unifrac_pcoa_results.qza',
    '2023.9/tutorials/otu-clustering/seqs.fna':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/otu-clustering/seqs.fna',
    '2023.9/tutorials/otu-clustering/85_otus.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/otu-clustering/85_otus.qza',
    '2023.9/tutorials/pd-mice/animal_distal_gut.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/pd-mice/animal_distal_gut.qza',
    '2023.9/tutorials/pd-mice/demultiplexed_seqs.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/pd-mice/demultiplexed_seqs.zip',
    '2023.9/tutorials/pd-mice/manifest':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/pd-mice/manifest',
    '2023.9/tutorials/pd-mice/ref_seqs_v4.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/pd-mice/ref_seqs_v4.qza',
    '2023.9/tutorials/pd-mice/ref_tax.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/pd-mice/ref_tax.qza',
    '2023.9/tutorials/quality-control/qc-mock-3-expected.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/quality-control/qc-mock-3-expected.qza',
    '2023.9/tutorials/quality-control/qc-mock-3-observed.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/quality-control/qc-mock-3-observed.qza',
    '2023.9/tutorials/quality-control/query-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/quality-control/query-seqs.qza',
    '2023.9/tutorials/quality-control/reference-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/quality-control/reference-seqs.qza',
    '2023.9/tutorials/quality-control/query-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/quality-control/query-table.qza',
    '2023.9/tutorials/read-joining/atacama-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/read-joining/atacama-seqs.qza',
    '2023.9/tutorials/read-joining/fj-joined.zip':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/read-joining/fj-joined.zip',
    '2023.9/tutorials/sample-classifier/atacama-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/sample-classifier/atacama-table.qza',
    '2023.9/tutorials/sample-classifier/moving-pictures-table.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/sample-classifier/moving-pictures-table.qza',
    '2023.9/tutorials/training-feature-classifiers/85_otu_taxonomy.txt':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/training-feature-classifiers/85_otu_taxonomy.txt',
    '2023.9/tutorials/training-feature-classifiers/85_otus.fasta':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/training-feature-classifiers/85_otus.fasta',
    '2023.9/tutorials/training-feature-classifiers/rep-seqs.qza':
        'https://s3-us-west-2.amazonaws.com/qiime2-data/2023.9/tutorials/training-feature-classifiers/rep-seqs.qza',
    '2023.9/tutorials/phylogeny/rep-seqs.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/phylogeny/rep-seqs.qza',
    '2023.9/tutorials/utilities/faith-pd-vector.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/utilities/faith-pd-vector.qza',
    '2023.9/tutorials/utilities/jaccard-pcoa.qza':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/utilities/jaccard-pcoa.qza',
    '2023.9/tutorials/utilities/taxa-barplot.qzv':
        'https://qiime2-data.s3-us-west-2.amazonaws.com/2023.9/tutorials/utilities/taxa-barplot.qzv',
    '2023.9/tutorials/liao/fmt-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/fmt-metadata.tsv',
    '2023.9/tutorials/liao/sample-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/sample-metadata.tsv',
    '2023.9/tutorials/liao/transplant-metadata.tsv':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/transplant-metadata.tsv',
    '2023.9/tutorials/liao/rep-seqs.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/rep-seqs.qza',
    '2023.9/tutorials/liao/full-feature-table.qza':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/full-feature-table.qza',
    '2023.9/tutorials/liao/fastq-casava.zip':
        'https://qiime2-data.s3.us-west-2.amazonaws.com/2023.9/tutorials/liao/fastq-casava.zip',

    # Sample Metadata (hosted on Google Sheets)
    ## All of the following tutorials use the *new* docs sharing menu, via "File -> Publish to the Web" dialog for TSV export.

    ## FMT
    '2023.9/tutorials/fmt/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1LSgWv1kXKGh7YOQAODmsrA4QmOmpKVMkNKaJlCkNDKw/edit?usp=sharing',
    '2023.9/tutorials/fmt/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vTuWqGEvYOerABcCoOXRCWDA5cPd_zyUNNO8CiqqMVaK_T5lMKkxLZAg3m6ncjxqHYLr3dvBvXXQj6M/pub?gid=0&single=true&output=tsv',

    ## Moving Pictures
    '2023.9/tutorials/moving-pictures/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1VtOfi0OzR8ATIAIOcj8mR-EVJyQyH6FD6CaFF6T744A/edit?usp=sharing',
    '2023.9/tutorials/moving-pictures/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQl5YGiG1SrYBxMg9ijh7qN6come0NKRxhIRt4-1WuIcNj0NXHn46SWRXmJ2_SpvVpHDCOHeFhVg2U_/pub?gid=0&single=true&output=tsv',

    ## Atacama
    '2023.9/tutorials/atacama-soils/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1MNh2ZFX4rRhtDc5FjVDlzhZ4FoWKl5pgC4J5ukV6Nh4/edit?usp=sharing',
    '2023.9/tutorials/atacama-soils/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQu-16nXMdkLLGxA3vgoGZ39MHPy-4QmdaW85TuZvzCRcnES0g73hnFR81E6B7NduOITqAVS1xK-bAj/pub?gid=0&single=true&output=tsv',

    ## Longitudinal
    '2023.9/tutorials/longitudinal/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1mXVqcB5pPXKu8zC8XLVLbTh5h0HvupOGS0N5IEU_JUE/edit?usp=sharing',
    '2023.9/tutorials/longitudinal/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vQnVba5aqZ-BioRwzzpXfrt2PQwBMmXR5H_3AbougEsdMDg0eIIzaVvJOoce7xDjwUDwf9JK-n-EhH4/pub?gid=1303657428&single=true&output=tsv',

    ## PD Mice
    '2023.9/tutorials/pd-mice/sample_metadata':
        'https://docs.google.com/spreadsheets/d/1I1w7yt3377I0FhcrO6X8LRSc9VS6Z8T70vuPlPXsga0/edit?usp=sharing',
    '2023.9/tutorials/pd-mice/sample_metadata.tsv':
        'https://docs.google.com/spreadsheets/d/e/2PACX-1vR7rCtY6th5jjscrsptylPJjXQaBN6wceAMywbbzj7v8_FoidivwBN9iFuEBER5bIZ2WzHaGzRaqgEA/pub?gid=1509704122&single=true&output=tsv',
}
