name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: set up python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint and test
      run: |
        pip install -q flake8
        flake8
        pip install -r requirements.txt
        python manage.py validate

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: deploy to dokku instance
        # Replaces idoberko2/dokku-deploy-github-action@v1
        uses: qiime2-cutlery/dokku-deploy-github-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'data.qiime2.org'
          app-name: 'webapp'
          # break in case of emergencies:
          # git-push-flags: --force
